---
title: 'Homework #5'
author: "Alex Alon"
date: "2024-10-21"
output:
  pdf_document: default
  word_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'Data')
```

Due date: Nov. 18 by midnight

You will submit this
project by sending me the link to a GitHub repository. 
For the write-up
of this homework, you'll need to write an RMarkdown document and render
it to a pdf file within the R Project for the GitHub repository.

```{r}
library(tidyverse)
library(purrr)
library(ggplot2)
library(broom)
library(tigris)
library(maps)
library(sf)
library(viridis)

homicides <- read.csv('homicide-data.csv')

homicides <- homicides %>%
  mutate(state = replace(state, state == "wI", "WI")) %>%
  mutate('city_name' =  paste(homicides$city, homicides$state, sep = ", "))

#group_by city
#sum of unsolved homicides
unsolved <- homicides %>%
  group_by(city_name) %>%
  mutate("unsolved_homicides" = disposition %in% c("Closed without arrest", "Open/No arrest"))


#I'm most interested in Los Angeles

LA <- unsolved %>%
  filter(city_name == "Los Angeles, CA")

us_states <- data.frame(state= state.name, area = state.area, region = state.region)

la_subdivisions <- county_subdivisions(state = "CA", county = "Los Angeles", cb = TRUE, class = "sf")

la_blocks <- block_groups(state = "CA", county = "Los Angeles", cb = TRUE, class = "sf")

la_tracts <- tracts(state = "CA", county = "Los Angeles", cb = TRUE, class = "sf")

la_county <- counties(state = "CA", cb = TRUE, class = "sf") %>%
  filter(NAME=="Los Angeles")


top3_race <- LA %>%
  group_by(victim_race) %>%
  count()

LA <- st_as_sf(LA, coords = c("lon", "lat"))%>% 
  st_set_crs(4269) %>%
  filter(victim_race %in% c("White", "Black", "Hispanic")) %>%
  mutate(unsolved_homicides = as.character(unsolved_homicides)) 


la_labs <- as_labeller(c( "TRUE" = "Unsolved Homicides", "FALSE" = "Solved Homicides"))

ggplot() +
  geom_sf(data =la_county, color = 'black', 
          fill = 'lightgrey') +
  geom_sf(data =la_subdivisions,  color = 'black', 
          fill = 'lightgrey', alpha = 0.25) +
  geom_sf(data =la_blocks,  color = 'black', 
          fill = 'lightgrey', alpha = 0.25)  +
  geom_sf(data =la_tracts,  color = 'black', 
          fill= 'lightgrey', alpha = 0.25) +
  geom_sf(data=LA,  aes(color = victim_race), size = 1.5) +
  facet_wrap(~unsolved_homicides, labeller = la_labs) +
  scale_color_viridis(discrete=TRUE) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(), axis.text.x=element_blank()) +
  theme(strip.text = element_text(size = 10, face='bold')) +
  labs(title = "Homicides in Los Angeles County", color = "Victim Race")
  
```